apiVersion: v1
kind: Secret
metadata:
  name: floci-cloud-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  token: {{ .Values.auth.token | default (randAlphaNum 32) | quote }}
{{- if .Values.auth.clerk.secretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: floci-cloud-clerk
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  secret-key: {{ .Values.auth.clerk.secretKey | quote }}
{{- end }}
